config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "artists#index"


    resources :artists do
      collection do
        get 'order_by_name'
        get 'order_by_created_at'
      end
    end


    resources :songs do
      collection do
        get 'delete_all_songs'
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  validates :name, presence: true

    def self.order_by_name
      order(:name)
    end

    def self.order_by_created_at
      order(:created_at)
    end

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    def index
      @artists = Artist.all.order(params[:sort])
      @song = Song.new
     end


    def show
      @artist = Artist.find(params[:id])
      @songs = @artist.songs
    end


    def order_by_name
      @artists = Artist.order_by_name
      render action: :index
    end

    def order_by_created_at
      @artists = Artist.order_by_created_at
      render action: :index

    end
  end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
    @song = Song.new
  end

  def create
    @song = Song.create(song_params)

    respond_to do |format|
      # if the response format is html, redirect as usual.
      format.html { redirect_to root_path }

      # if the response format is javascript, do something else.
      format.js { }
    end
  end


  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { }
    end
  end



  def delete_all_songs
    @artist = Artist.find(params[:id])
    @songs = @artist.songs
    @songs.each do |a|
      a.destroy
    end

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { }
    end
  end



  private

  def song_params
    params.require(:song).permit(:name, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  module ApplicationHelper
    def sortable(name, title = nil)
      title ||= name.titleize
      direction = (name == sort_name && sort_direction == "asc") ? "desc" : "asc"
      link_to title, :sort => column, :direction => direction
    end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <div class="col-md-7 col-md-offset-3">
    <div class="col-md-9">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3>Artists</h3>
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Sort by
              <span class="caret"></span></button>
            <ul class="dropdown-menu">
              <li> <%= link_to "Name", order_by_name_artists_path %></li>
              <li><%= link_to "Added on", order_by_created_at_artists_path %></li>
              <!--<li> <%#= link_to "Name", :sort => "name" %></li>-->
              <!--<li><%#= link_to "Added on", :sort => "created_at" %></li>-->
            </ul>
          </div>
        </div>
          <div class="panel-body">

            <% @artists.each do |artist| %>
                <div class="img-thumbnail"><%= image_tag artist.image, class: "img-responsive", :size => '250x250' %></div><br>
                <h4><%= link_to artist.name, artist_path(artist.id), class: "btn btn-default", id: "artist_link" %></h4><br>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</html>

app/views/artists/show.html.erb
<!DOCTYPE html>
<html lang="en">
<div class="col-md-7 col-md-offset-3">

  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h1><%= @artist.name %></h1>
      </div>
      <div class="panel-body">

        <p><%= image_tag @artist.image, class: "img-responsive", size: '300x300', class: "centerImage"  %></p>
        <br>
        <h4>Biography</h4>
        <br>
         <%= @artist.bio %>
        <br><br>
         <h4>List of Songs</h4>

          <ul class="list-unstyled">
            <% @artist.songs.each do |song| %>
                <!--'id' will help find the correct element you want to remove.-->
                <li id="<%= song.id %>">
                  <%= song.name %><br>
                  <%= link_to "delete", song_path(song), method: 'delete', remote: true %>
                </li>
            <% end %>
          </ul>

        <div>
         <%= render 'songs/form' %>
        </div>
        <div>
          <%= link_to "Remove all songs", delete_all_songs_songs_path(id: @artist.id), action:'delete_all_songs', class: "btn btn-default", data: {confirm: "This will remove all the songs for this artist. Are you Sure?", remote: true, } %>
        </div><br>
        <div>
          <%= link_to "Back", root_path, class: "btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Songdb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/songs/_form.html.erb
<div class="songs-form">

<%= form_for Song.new, remote: true do |f| %>
    <div class="form-group">
      <%= f.text_field :name, placeholder: "Add a song", id: "song_input" %>
    </div>

    <div class="form-group">
      <%= f.hidden_field(:artist_id, value: @artist.id) %>
    </div>

    <div class="form-group">
      <%= f.submit "Add Song", class: "btn btn-default", id: "submit_song" %>
    </div>
  <% end %>

</div>

app/views/songs/create.js.erb
// Remote true points to the create.js.erb file.
var html = "<li><%= @song.name %><br><%= escape_javascript link_to 'delete', song_path(@song), method: 'delete', remote: true %></li>";

// Makes sure field is empty after submitting.
$('#song_input').val('');

// Tells the new song where to appear on the page.
$('ul').append(html);

app/views/songs/delete_all_songs.js.erb
$("li#<%= @songs.id %>");

app/views/songs/destroy.js.erb
$("li#<%= @song.id %>").slideUp();